SET SQL DIALECT 3;

CREATE TABLE TIPO_ENDERECO (
  ID INTEGER NOT NULL,
  DSC_ENDERECO VARCHAR(15));

  COMMIT WORK;

ALTER TABLE TIPO_ENDERECO ADD PRIMARY KEY (ID) USING INDEX RDB$PRIMARY5;

COMMIT WORK;

CREATE TABLE ENTIDADE_ENDERECO (
  ID INTEGER NOT NULL,
  COD_ENTIDADE INTEGER NOT NULL,
  COD_TIPO_ENDERECO INTEGER NOT NULL,
  CEP VARCHAR(10),
  LOGRADOURO VARCHAR(150),
  NUMERO INTEGER,
  FLG_SEM_NUMERO SMALLINT DEFAULT 0 NOT NULL,
  COMPLEMENTO VARCHAR(20),
  BAIRRO VARCHAR(100),
  CIDADE VARCHAR(100),
  ESTADO VARCHAR(40),
  PAIS VARCHAR(50));

COMMIT WORK;

ALTER TABLE ENTIDADE_ENDERECO ADD PRIMARY KEY (ID) USING INDEX RDB$PRIMARY4;

COMMIT WORK;

CREATE GENERATOR ENTIDADE_ENDERECO_ID_GEN;

SET TERM ^ ;

CREATE TRIGGER BI_ENTIDADE_ENDERECO_ID FOR ENTIDADE_ENDERECO
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(ENTIDADE_ENDERECO_ID_GEN, 1);
END^

SET TERM ; ^


CREATE TABLE TIPO_ENTIDADE (
  ID INTEGER NOT NULL,
  DSC_ENTIDADE VARCHAR(18));

ALTER TABLE TIPO_ENTIDADE ADD PRIMARY KEY (ID) USING INDEX RDB$PRIMARY2;

CREATE TABLE TIPO_PESSOA (
  ID INTEGER NOT NULL,
  DSC_PESSOA VARCHAR(12));


ALTER TABLE TIPO_PESSOA ADD PRIMARY KEY (ID) USING INDEX RDB$PRIMARY3;

CREATE TABLE ENTIDADE (
  ID INTEGER NOT NULL,
  COD_TIPO_ENTIDADE INTEGER,
  COD_TIPO_PESSOA INTEGER,
  NOME VARCHAR(200),
  CPF_CNPJ VARCHAR(18),
  IDENTIDADE VARCHAR(20),
  EMAIL VARCHAR(100),
  COD_ENTIDADE_ENDERECO INTEGER);


ALTER TABLE ENTIDADE ADD PRIMARY KEY (ID) USING INDEX RDB$PRIMARY1;

CREATE INDEX IDX_ENTIDADE ON ENTIDADE(ID,NOME);

CREATE GENERATOR ENTIDADE_ID_GEN;

SET TERM ^ ;

CREATE TRIGGER BI_ENTIDADE_ID FOR ENTIDADE
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(ENTIDADE_ID_GEN, 1);
END^

SET TERM ; ^

CREATE GENERATOR TIPO_ENDERECO_ID_GEN;

SET GENERATOR TIPO_ENDERECO_ID_GEN TO 4;

SET TERM ^ ;

CREATE TRIGGER BI_TIPO_ENDERECO_ID FOR TIPO_ENDERECO
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(TIPO_ENDERECO_ID_GEN, 1);
END^

SET TERM ; ^

CREATE GENERATOR TIPO_ENTIDADE_ID_GEN;

SET GENERATOR TIPO_ENTIDADE_ID_GEN TO 5;

SET TERM ^ ;

CREATE TRIGGER BI_TIPO_ENTIDADE_ID FOR TIPO_ENTIDADE
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(TIPO_ENTIDADE_ID_GEN, 1);
END^

SET TERM ; ^

CREATE GENERATOR TIPO_PESSOA_ID_GEN;

SET GENERATOR TIPO_PESSOA_ID_GEN TO 2;

SET TERM ^ ;

CREATE TRIGGER BI_TIPO_PESSOA_ID FOR TIPO_PESSOA
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(TIPO_PESSOA_ID_GEN, 1);
END^

SET TERM ; ^

SET TERM ^ ;

CREATE OR ALTER PROCEDURE MY_PROC
RETURNS(
  APARAM INTEGER)
AS
BEGIN  aParam = 10;END^

SET TERM ; ^

INSERT INTO TIPO_ENDERECO
VALUES (1, 'EMPRESA');

INSERT INTO TIPO_ENDERECO
VALUES (2, 'RESIDENCIA');

INSERT INTO TIPO_ENDERECO
VALUES (3, 'FATURAMENTO');

INSERT INTO TIPO_ENDERECO
VALUES (4, 'ENTREGA');

INSERT INTO TIPO_ENDERECO
VALUES (5, 'OUTROS');

COMMIT WORK;

INSERT INTO TIPO_ENTIDADE
VALUES (1, 'CLIENTE');

INSERT INTO TIPO_ENTIDADE
VALUES (2, 'FORNECEDOR');

INSERT INTO TIPO_ENTIDADE
VALUES (3, 'TERCERIZADO');

INSERT INTO TIPO_ENTIDADE
VALUES (4, 'COLABORADOR');

INSERT INTO TIPO_ENTIDADE
VALUES (5, 'OUTROS');

COMMIT WORK;

INSERT INTO TIPO_PESSOA
VALUES (1, 'FÍSICA');

INSERT INTO TIPO_PESSOA
VALUES (2, 'JURÍDICA');

COMMIT WORK;

ALTER TABLE ENTIDADE ADD CONSTRAINT FK_ENTIDADE_ENDERECO FOREIGN KEY (COD_ENTIDADE_ENDERECO) REFERENCES ENTIDADE_ENDERECO(ID) ON UPDATE CASCADE;

ALTER TABLE ENTIDADE ADD CONSTRAINT FK_TIPO_ENTIDADE FOREIGN KEY (COD_TIPO_ENTIDADE) REFERENCES TIPO_ENTIDADE(ID) ON UPDATE CASCADE;

ALTER TABLE ENTIDADE ADD CONSTRAINT FK_TIPO_PESSOA FOREIGN KEY (COD_TIPO_PESSOA) REFERENCES TIPO_PESSOA(ID) ON UPDATE CASCADE;

ALTER TABLE ENTIDADE_ENDERECO ADD CONSTRAINT FK_TIPO_ENDERECO FOREIGN KEY (COD_TIPO_ENDERECO) REFERENCES TIPO_ENDERECO(ID) ON UPDATE CASCADE;

GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON ENTIDADE TO SYSDBA WITH GRANT OPTION;


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON ENTIDADE_ENDERECO TO SYSDBA WITH GRANT OPTION;


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TIPO_ENDERECO TO SYSDBA WITH GRANT OPTION;


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TIPO_ENTIDADE TO SYSDBA WITH GRANT OPTION;


GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TIPO_PESSOA TO SYSDBA WITH GRANT OPTION;

GRANT EXECUTE ON PROCEDURE MY_PROC TO SYSDBA;

